# centos6-epel
#
# VERSION               0.1.2

FROM centos:centos6
MAINTAINER Yuu Yamanaka <yuu@relx.jp>

RUN yum update -y && yum clean all
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
